// 国家名称到 ISO 代码映射
export const countryNameToCode: Record<string, string> = {
    'china': 'cn',
    'japan': 'jp',
    'south korea': 'kr',
    'north korea': 'kp',
    'mongolia': 'mn',
    'taiwan': 'tw',
    'india': 'in',
    'pakistan': 'pk',
    'bangladesh': 'bd',
    'nepal': 'np',
    'afghanistan': 'af',
    'sri lanka': 'lk',
    'indonesia': 'id',
    'thailand': 'th',
    'vietnam': 'vn',
    'philippines': 'ph',
    'malaysia': 'my',
    'singapore': 'sg',
    'myanmar': 'mm',
    'cambodia': 'kh',
    'laos': 'la',
    'turkey': 'tr',
    'iran': 'ir',
    'saudi arabia': 'sa',
    'iraq': 'iq',
    'israel': 'il',
    'jordan': 'jo',
    'lebanon': 'lb',
    'syria': 'sy',
    'egypt': 'eg',
    'united arab emirates': 'ae',
    'kuwait': 'kw',
    'qatar': 'qa',
    'bahrain': 'bh',
    'oman': 'om',
    'yemen': 'ye',
    'russia': 'ru',
    'germany': 'de',
    'france': 'fr',
    'italy': 'it',
    'spain': 'es',
    'poland': 'pl',
    'ukraine': 'ua',
    'united kingdom': 'gb',
    'netherlands': 'nl',
    'belgium': 'be',
    'sweden': 'se',
    'austria': 'at',
    'switzerland': 'ch',
    'greece': 'gr',
    'czech republic': 'cz',
    'romania': 'ro',
    'hungary': 'hu',
    'nigeria': 'ng',
    'south africa': 'za',
    'kenya': 'ke',
    'ethiopia': 'et',
    'ghana': 'gh',
    'tanzania': 'tz',
    'uganda': 'ug',
    'zambia': 'zm',
    'zimbabwe': 'zw',
    'malawi': 'mw',
    'united states': 'us',
    'united states of america': 'us',
    'mexico': 'mx',
    'brazil': 'br',
    'colombia': 'co',
    'argentina': 'ar',
    'peru': 'pe',
    'chile': 'cl',
    'canada': 'ca',
    'guatemala': 'gt',
    'cuba': 'cu',
    'ecuador': 'ec',
}

export function nameToCode(name: string): string {
    return countryNameToCode[name.toLowerCase()] ?? name.toLowerCase()
}
